name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macOS-11.0
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Run tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.5.1.app
      run: xcodebuild test -scheme Xcodes
